### ISSUE TITLE
Domain name change

### ISSUE THREAD

**Issue by Mikle-Bond** [BananaAcid/chocolatey-appstore#2]
Chocolatey packages now live on https://community.chocolatey.org/packages instead of just https://chocolatey.org/packages.
The `chocolatey-appstore-theme/manifest.json` should be updated accordingly.

**Comment by ghost** [comment]
exactly, it need to be updated

**Comment by BananaAcid** [comment]
fixed in https://github.com/BananaAcid/chocolatey-appstore/commit/6a405e5ef61997f55b09313ce91a8729c6b482a3
